name: Deploy prod tmmk site on push main

on:
  push:
    branches:
      - main

jobs:
  web-deploy:

    name: Deploy tmmk site
    runs-on: ubuntu-latest

    env:
      SERVER: tmmk.info

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 16 LTS
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build
  
#     - name: Export Static Project
#       run: npm run exp

#     - name: Sync Files
#       uses: SamKirkland/FTP-Deploy-Action@4.0.0
#       with:
#         server: ${{ env.SERVER }}
#         username: ${{ secrets.ftp_username}}
#         password: ${{ secrets.ftp_password }}
#         server-dir: /
#         local-dir: ./out/
        #dangerous-clean-slate: true

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSHHOST }}
        username: ${{ secrets.SSHUSERNAME }}
        password: ${{ secrets.SSHPASSWORD }}
#         port: 80
        script: |
          cd ../home/tmmk/public_html/tmmk-site
          git restore package-lock.json
          git pull origin main
          git status
          npm install
          pm2 restart tmmk-site
